import { StyleSheet } from 'react-native';
import colors from "../../config/color/color";
import FontFamily from "../../config/fonts/fontfamily";

const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colors.white,
    },
    scrolledview:{
        flex:1,
        paddingLeft:15,
        paddingRight:15,
    },
    heading:{
        fontFamily:FontFamily.Medium,
        fontSize:20,
        color:colors.black
    },
    barSearchChips:{
      marginTop:13,
    },
    customchip:{
      flexDirection:'row',
      alignItems:'center',
      backgroundColor:colors.lightGray,
      padding:10,
      paddingLeft:15,
      paddingRight:15,
      borderRadius:20,
      marginRight:8
    },
    customchiptext:{
      fontFamily:FontFamily.Medium,
      marginLeft:8
    },
    separator:{
      marginTop:13,
      marginBottom:13,
    },
    roundedtextinputcontainer:{
        backgroundColor:colors.lightGray,
        borderRadius:6,
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:10,
        paddingRight:10,
        height: 40,
        flex:1,
    },
    boxShadow:{
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.20,
      shadowRadius: 1.41,
      elevation: 2,
    },
    roundedtextinput:{
        flex:1,
        height:"100%",
        paddingLeft:5,
    },
    roundedfilterinputcontainer:{
         marginTop:13,
        flexDirection:'row',
        alignItems:'center'
    },
    filterIcon:{
      backgroundColor:colors.lightGray,
      borderRadius:6,
      flexDirection:'row',
      alignItems:'center',
      paddingLeft:10,
      paddingRight:10,
      height: 40,
      marginLeft:10
    },
    restaurantsContainer:{
      marginTop:15
    },
    barImage:{
      resizeMode: "cover",
      minHeight:200,
      maxHeight:200,
      paddingTop:8,
      paddingBottom:8,
      flexDirection:'column',
      justifyContent:'space-between',
    },
    labelFavList:{
      flexDirection:'row',
      justifyContent:'space-between',
    },
    iconOpacity:{
      padding:10,
      paddingTop:5
    },
    startLabelContainer:{
      alignItems:'flex-start'
    },
    redLabel:{
      backgroundColor:'#D70F64',
      borderTopRightRadius:6,
      borderBottomRightRadius:6,
      marginBottom:6,
      paddingLeft:10,
      paddingRight:10,
      paddingTop:3,
      paddingBottom:3,
    },
    redLabelText:{
      fontFamily:FontFamily.Medium,
      fontSize:14,
      color:colors.white,
    },
    whiteLabel:{
      backgroundColor:colors.white,
      borderRadius:20,
      marginLeft:6,
      paddingLeft:10,
      paddingRight:10,
      paddingTop:5,
      paddingBottom:5,
    },
    whiteLabelText:{
      fontFamily:FontFamily.Medium,
      fontSize:14,
      color:colors.black
    },
    barTitleRatingContainer:{
      flexDirection:'row',
      justifyContent:'space-between',
      alignItems:'center',
      marginTop:10
    },
    barTitleList:{
      flexDirection:'row',
      justifyContent:'space-between',
      alignItems:'center'
    },
    barTitle:{
      fontFamily:FontFamily.Medium,
      fontSize:16,
      color:colors.black
    },
    textBold:{
      fontFamily:FontFamily.Medium,
      fontSize:14,
      color:colors.black
    },
    textGray:{
      fontFamily:FontFamily.Regular,
      fontSize:14,
      color:colors.gray
    },
    barTitleDash:{
      width:5,
      height:2,
      backgroundColor:colors.black,
      marginLeft:5,
      marginRight:5,
    },
    barRatingComment:{
      flexDirection:'row',
      alignItems:'center'
    },
    flavourContainer:{
      marginTop:5,
      flexDirection:'row',
      alignItems:'center'
    },
    dot:{
      width:3,
      borderRadius:20,
      height:3,
      backgroundColor:colors.gray,
      marginLeft:3,
      marginRight:3,
    },
    priceRangeContainer:{
      marginTop:5,
      flexDirection:'row',
      alignItems:'center'
    }
  });
  
export default styles;