import { StyleSheet } from 'react-native';
import colors from "../../config/color/color";
import FontFamily from "../../config/fonts/fontfamily";

const styles = StyleSheet.create({
    container:{
      flex:1,
      backgroundColor:colors.white,
    },
    scrolledview:{
      flex:1,
      paddingLeft:15,
      paddingRight:15,
      paddingTop:13,
    },
    heading:{
      fontFamily:FontFamily.Medium,
      fontSize:20,
      color:colors.black
    },
    text:{
      fontFamily:FontFamily.Regular,
      fontSize:15,
      color:colors.black
    },
    labeltext:{
      fontFamily:FontFamily.Medium,
      fontSize:15,
      color:colors.black
    },
    rulelabeltext:{
      fontFamily:FontFamily.Medium,
      fontSize:15,
      color:colors.black,
      textTransform:'uppercase'
    },
    graytext:{
      fontFamily:FontFamily.Regular,
      fontSize:13,
      color:colors.gray
    },
    primarytext:{
      fontFamily:FontFamily.Regular,
      fontSize:15,
      color:colors.primary
    },
    listcontainer:{
      flexDirection:'row',
      alignItems:'flex-start',
      paddingTop:10,
      paddingBottom:10,
    },
    modallist:{
      fontSize:17,
      fontFamily:FontFamily.Regular,
    },
    listcontainerright:{
      marginLeft:10,
      flex:1
    },
    grouplocation:{
      flexDirection:'row',
      flexWrap:'wrap',
      alignItems:'center'
    },
    dot:{
      width:3,
      height:3,
      backgroundColor:colors.black,
      borderRadius:20,
      marginLeft:5,
      marginRight:5
    },
    separtor:{
      marginTop:5,
      marginBottom:13
    },
    seeallcontainer:{
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'space-between',
      marginBottom:13
    },
    touchopacity:{
      paddingLeft:10,  
    },
    mutualimagescontainer:{
      flexDirection:'row',
    },
    avatarimage:{
      marginRight:10,
      backgroundColor:colors.white
    },
    mutualimages:{
      borderRadius:30,
      borderLeftWidth:1,
      borderColor:colors.white,
      backgroundColor:colors.white
    },
    lastcomponents:{
      marginTop:5,
      marginBottom:30,
    }
  });
  
export default styles;