import { StyleSheet } from 'react-native';
import colors from "../../config/color/color";
import FontFamily from "../../config/fonts/fontfamily";
import { Dimensions } from 'react-native';

const windowWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
    container:{
      flex:1,
      backgroundColor:colors.white,
    },
    scrolledview:{
      flex:1,
    },
    separator:{
      margin:13
    },
    noMarginBottom:{
      marginBottom:0
    },
    sideSpace:{
      paddingLeft:15,
      paddingRight:15,
    },
    NewTimeSort:{
      marginTop:13,
    },
    notificationTimeSort:{
      fontFamily:FontFamily.Medium,
      fontSize:18,
      color:colors.black,
      paddingLeft:15,
      paddingRight:15,
      marginBottom:13,
    },
    list:{
      flexDirection:'row',
      paddingTop:7,
      paddingBottom:7,
      paddingLeft:15,
      paddingRight:15,
    },
    listLeft:{
      marginRight:8,
    },
    listRight:{
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'space-between',
      flex:1,
    },
    listContent:{
      flex:1,
    },
    listNameContent:{
    },
    dotsOpacity:{
      padding:6
    },
    textBold:{
      fontFamily:FontFamily.Medium,
      fontSize:14,
      color:colors.black
    },
    text:{
      fontSize:14,
      fontFamily:FontFamily.Regular,
      color:colors.black
    },
    textGray:{
      fontSize:12,
      fontFamily:FontFamily.Regular,
      color:colors.gray
    },
    unreadNotification:{
      backgroundColor:colors.lightGray,
      borderRadius:6
    },
    heading:{
      fontFamily:FontFamily.Medium,
      fontSize:18,
      color:colors.black
    },
    seealltext:{
      fontFamily:FontFamily.Regular,
      fontSize:15,
      color:colors.primary
    },
    
    pendinginvitescontainer: {
      flexDirection:'row',
      backgroundColor:'#fff',
      justifyContent:'flex-start',
      marginBottom:15
    },
    pendinginvitesnamecontainer:{
      flex:1,
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'space-between',
    },
    username: {
      color:colors.black,
      fontSize: 18,
      fontFamily: FontFamily.Medium,
    },
    mutualimagescontainer:{
      flexDirection:'row',
      marginRight:5,
    },
    avatarimage:{
      backgroundColor:colors.white
    },
    mutualimages:{
      borderRadius:30,
      borderLeftWidth:1,
      borderColor:colors.white,
      backgroundColor:colors.white
    },
    mutualtextimagescontainer:{
      flexDirection:'row',
      alignItems:'center',
      marginTop:3
    },
    multibtns:{
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'center',
      marginTop:5
    },
    primarybtn:{
      flex:1,
      backgroundColor:colors.primary,
      padding:7,
      borderRadius:6,
      marginRight:5 
    },
    primarybtntext:{
      color:colors.white,
      fontSize:12,
      textAlign:'center',
      fontFamily:FontFamily.Medium
    },
    graybtn:{
      flex:1,
      backgroundColor:colors.lightGray,
      padding:7,
      borderRadius:6,
      marginLeft:5
    },
    graybtntext:{
      color:colors.black,
      fontSize:12,
      textAlign:'center',
      fontFamily:FontFamily.Medium
    }
  });
  
export default styles;