import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    borderTopWidth: 1,
    borderTopColor: 'lightgrey',
    paddingVertical: 12,
    
  },
  activityIndicator: {
    position: 'absolute',
    alignSelf: 'center',
    paddingTop: 25,
  },
  textInput: {
    flex: 1,
    fontSize: 18,
    fontWeight: '300',
    color: '#8c8c8c',
    borderRadius: 25,
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'ios' ? 14 : 10,
    paddingBottom: Platform.OS === 'ios' ? 14 : 10,
    paddingRight: 30,
    backgroundColor: 'whitesmoke',
  },
  button: {
    width: 30,
    height: 30,
    marginBottom: Platform.OS === 'ios' ? 15 : 0,
    marginLeft: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachment: {
    width: 40,
    height: 50,
    position: 'absolute',
    right: 5,
    bottom: 0,
    marginLeft: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  indicator: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  inputContainer: {
    marginBottom: Platform.OS === 'ios' ? 15 : 0,
    flexDirection: 'row',
    width:'70%',
  },
  chatContainer: {
    borderRadius: 15,
    margin: 5,
  },
  chatTxt: {
    color: '#fff',
    fontSize: 16,
    marginVertical: 5,
    fontWeight: "500",
    padding: 8,
  },
  activityIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  senderMessage:{ paddingVertical: 10, paddingHorizontal:10,  justifyContent:'flex-end', alignItems:'flex-end'},
  sendImage:{ borderColor:'#03a5fc', marginBottom: 3, borderWidth:5, borderBottomRightRadius:10,borderBottomLeftRadius:10,  borderTopLeftRadius:10,},
  sendImageTime: {alignSelf: 'flex-end', textAlign:'right',paddingHorizontal: 3,  paddingTop: 10,fontSize: 13, color: '#ffffff',marginTop: -40, marginRight:10, marginBottom:10},
  sendMessageText:{ backgroundColor:'#03a5fc', borderBottomRightRadius:20,borderBottomLeftRadius:20, borderTopLeftRadius:20, paddingVertical:15, paddingHorizontal:15},
  recieveMessageTime: {alignSelf: 'flex-end', textAlign:'right', paddingTop: 1,paddingHorizontal: 3,fontSize: 12, color: 'lightcyan'},
  recieveMessageView: { paddingVertical: 5, paddingHorizontal:10,  justifyContent:'flex-start', alignItems:'flex-start'},
  recieveMessageText: {backgroundColor:'#cae8ed', borderBottomRightRadius:20,borderBottomLeftRadius:20,  borderTopRightRadius:20, paddingVertical:10, paddingHorizontal:15},
  recieveTextTime:{alignSelf: 'flex-end', textAlign:'right',  paddingTop: 1,  paddingHorizontal: 3, fontSize: 12, color: '#171717'},
  recieveImage: { borderColor:'#cae8ed', marginBottom: 3, borderWidth:5, borderBottomRightRadius:10,borderBottomLeftRadius:10,  borderTopRightRadius:10, },
  chatImage: {width:300, height:140},
  centeredView: {
  
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    backgroundColor:'#25539c'
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  openButton: {
    backgroundColor: '#F194FF',
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  sendFileNameView:{ backgroundColor: '#0483c7', padding: 10, borderRadius: 10, flexDirection: 'row'},
  sendImagePosition:{flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end',},
  sendFileNameText:{fontSize: 16, color: '#ffffff'},
  sendFileTime: {color: '#ffff', textAlign: 'right'},
  sendMsgText:{fontSize: 16, color: '#ffffff'},
  recieveFileNameView:{backgroundColor: '#0483c7', padding: 10, borderRadius: 10, flexDirection: 'row' },
  recieveFileNameText:{fontSize: 16, color: '#ffffff'},
  sendFileTime:{ color: '#ffff', textAlign: 'right' },
  recievetext:{fontSize: 16, color: '#080a0a'},

});