const images = {
  ready: require('../../../../../assets/emoji/your-app.png'),
  api: require('../../../../../assets/emoji/Icons/icon-api-testing.png'),
  components: require('../../../../../assets/emoji/Icons/icon-components.png'),
  deviceInfo: require('../../../../../assets/emoji/Icons/icon-device-information.png'),
  faq: require('../../../../../assets/emoji/Icons/faq-icon.png'),
  home: require('../../../../../assets/emoji/Icons/icon-home.png'),
  theme: require('../../../../../assets/emoji/Icons/icon-theme.png'),
  usageExamples: require('../../../../../assets/emoji/Icons/icon-usage-examples.png'),
  chevronRight: require('../../../../../assets/emoji/Icons/chevron-right.png'),
  hamburger: require('../../../../../assets/emoji/Icons/hamburger.png'),
  backButton: require('../../../../../assets/emoji/Icons/back-button.png'),
  closeButton: require('../../../../../assets/emoji/Icons/close-button.png'),

  ic_back: require('../../../../../assets/emoji/ic_back.png'),
  like_gif: require('../../../../../assets/emoji/like.gif'),
  like_static: require('../../../../../assets/emoji/ic_like.png'),
  like_static_fill: require('../../../../../assets/emoji/ic_like_fill.png'),
  love_gif: require('../../../../../assets/emoji/love.gif'),
  love_static: require('../../../../../assets/emoji/love2.png'),
  haha_gif: require('../../../../../assets/emoji/haha.gif'),
  haha_static: require('../../../../../assets/emoji/haha2.png'),
  wow_gif: require('../../../../../assets/emoji/wow.gif'),
  wow_static: require('../../../../../assets/emoji/wow2.png'),
  sad_gif: require('../../../../../assets/emoji/sad.gif'),
  sad_static: require('../../../../../assets/emoji/sad2.png'),
  angry_gif: require('../../../../../assets/emoji/angry.gif'),
  angry_static: require('../../../../../assets/emoji/angry2.png'),
};

export default images;